modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/comedy01/Loupe/issues"

[[mods]]
modId="loupe"
version="${version}"
displayName="Loupe"
displayURL="https://github.com/comedy01/Loupe"
logoFile="assets/loupe/icon.png"
authors="comedy01"
description='''Hold a key to zoom in with a smooth animation, and scroll the mouse wheel to adjust the magnification. Client-side only.'''

[[mixins]]
config="loupe.mixins.json"

[[dependencies.loupe]]
modId="neoforge"
type="required"
versionRange="${neoforge_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.loupe]]
modId="minecraft"
type="required"
versionRange="${mc_range}"
ordering="NONE"
side="CLIENT"
