fabric_api_version=0.129.0+1.21.7
modmenu_version=15.0.2
packs=fov-renderer-float,screen-field,keys-binding,camera-reflect,key-category-string,hotbar-getter,default-key-z
label=1.21.7
range=1.21.7
java=21
key_module=fabric-key-binding-api-v1
