fabric_api_version=0.141.6+1.21.11
modmenu_version=17.0.1-beta.1
packs=fov-renderer-float,screen-field,keys-binding,camera-reflect,key-category-identifier,hotbar-getter,default-key-c
label=1.21.11
range=1.21.11
java=21
key_module=fabric-key-binding-api-v1
