fabric_api_version=0.116.17+1.21.1
modmenu_version=11.0.4
packs=fov-renderer-double,screen-field,keys-binding,camera-reflect,key-category-string,hotbar-field,default-key-z
label=1.21.1
range=1.21.1
java=21
key_module=fabric-key-binding-api-v1
gametest=false
