fabric_api_version=0.136.1+1.21.8
modmenu_version=15.0.2
packs=fov-renderer-float,screen-field,keys-binding,camera-reflect,key-category-string,hotbar-getter,default-key-z
label=1.21.8
range=1.21.8
java=21
key_module=fabric-key-binding-api-v1
