fabric_api_version=0.119.4+1.21.4
modmenu_version=13.0.4
packs=fov-renderer-float,screen-field,keys-binding,camera-reflect,key-category-string,hotbar-field,default-key-z
label=1.21.4
range=1.21.4
java=21
key_module=fabric-key-binding-api-v1
