fabric_api_version=0.134.1+1.21.9
modmenu_version=16.0.1
packs=fov-renderer-float,screen-field,keys-binding,camera-reflect,key-category-location,hotbar-getter,default-key-c
label=1.21.9-1.21.11
range=>=1.21.9 <1.22
java=21
key_module=fabric-key-binding-api-v1
