fabric_api_version=0.114.1+1.21.3
modmenu_version=12.0.1
packs=fov-renderer-float,screen-field,keys-binding,camera-reflect,key-category-string,hotbar-field,default-key-z
label=1.21.3
range=1.21.3
java=21
key_module=fabric-key-binding-api-v1
gametest=false
