fabric_api_version=0.155.3+26.1.2
modmenu_version=20.0.1
packs=fov-camera,screen-field,keys-mapping,camera-getmain,key-category-identifier,hotbar-getter,default-key-c
label=26.1
range=>=26.1 <26.2
java=25
key_module=fabric-key-mapping-api-v1
