fabric_api_version=0.161.0+26.2
modmenu_version=20.0.1
packs=fov-camera,screen-gui,keys-mapping,camera-main,key-category-identifier,hotbar-getter,default-key-c
label=26.2
range=>=26.2 <26.3
java=25
key_module=fabric-key-mapping-api-v1
