minecraft=26.4-snapshot-1
fabric_api_version=0.161.1+26.4
modmenu_version=20.0.1
packs=fov-camera,screen-gui,keys-mapping,camera-main,key-category-identifier,hotbar-getter,default-key-c
label=26.4-snapshot-1
range=>=26.4- <26.5-
java=25
key_module=fabric-key-mapping-api-v1
